---
pipeline:
  projectIdentifier: "storz_pp_sandbox"
  orgIdentifier: "SE_Sandbox"
  stages:
  - stage:
      name: "Build"
      identifier: "Build"
      type: "CI"
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              type: "Run"
              name: "Echo Welcome Message"
              identifier: "Echo_Welcome_Message"
              spec:
                shell: "Sh"
                command: "echo \"Welcome to Harness CI\""
        platform:
          os: "Linux"
          arch: "Amd64"
        runtime:
          type: "Cloud"
          spec: {}
  properties:
    ci:
      codebase:
        connectorRef: "account.Public_Github"
        repoName: "crizstian/ios_harness_demo"
        build: "<+input>"
  identifier: "Build_crizstian_ios_harness_demo_1713387396780_Clone"
  tags: {}
  name: "Build ios_harness_demo - Clone"
